### ISSUE TITLE
platform-ui: Migrate from Dockerhub to Github Packages

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/platform-ui#1774]
### Tasks
- [x] Update automation (Jenkinsfile) to push newly built docker images to ghcr.io registry
- [x] Push/upload image to github registry and make it public
- [x] Update helm chart to use new image location by default
- [x] Update values and re-deploy all helm chart releases based on the helm chart

### Inventory for helm chart releases to be re-deployed and validated:
**DEV/QA cluster:**
- [x] platform-ui - argo-qa 
- [x] platform-ui - argo-dev

**STAGING/PROD cluster:**
- [ ] platform-ui - argo-staging
- [ ] platform-ui - argo-prod

**Comment by yalturmes** [comment]
Staging and prod envs can be be tested only once the changes make it to master branch through the release process. Not closing this ticket for now in case additional troubleshooting required.

**Comment by yalturmes** [comment]
Jenkins pipelines for platform-ui look good after merging changes into master branch.
Closing ticket.
