### ISSUE TITLE
Update deprecated Storybook addons

### ISSUE THREAD

**Issue by samrichca** [icgc-argo/platform-ui#1811]
@storybook/addon-info and @storybook/addon-options are deprecated, and one of info's dependencies has a security vulnerability (nested-object-assign).

Migration info for these two packages:

https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#migrating-from-notesinfo-addons
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#options-addon-deprecated

## Analysis by Ciaran
- [ ] upgrade Storybook to latest release (6.1.?)
- [ ] ensure all addons we use are updated or we keep the functionality with a different addon (eg. info-addon => docs-addon)
- [ ] rewrite our story components (everything ending in *.stories.tsx) to use the new CSF format

Then our development will be aligned with how Storybook is developing (all their good documentation will be relevant again for any devs that are writing stories) and also all the usual bug fixes that come up with a major upgrade.

Rewriting the components is time consuming but should be straightforward. It's a matter of rewriting them in a different style.
There is a codemod which is a script to do it automatically but when I briefly tried it, I had no luck.

**Comment by ciaranschutte** [comment]
@rosibaj 
- the security warning is not appearing in Github so this is fine for now
- updating those addons is not needed and far beyond the scope of this ticket because they are completely deprecated
  - the fix is to upgrade to an entirely new addon which then requires rewriting all stories in a new format  https://storybook.js.org/docs/react/api/csf
- local running of Storybook is not broken, there was just an env var missing
  - I don't think any action is needed as it is in our `.env.schema` and noted to update these values in our readme https://github.com/icgc-argo/platform-ui/blob/develop/README.md#setup
  
  we can close this

**Comment by rosibaj** [comment]
@ciaranschutte  a  questions: 
- Since these are deprecated and we need to swap, at what point will that become a maintenance issue? (i.e should i plan for this upgrade)
- if it will become an issue, id rather remove this from sprint and keep in backlog pending scheduling.

**Comment by ciaranschutte** [comment]
It will be an issue though I can't say when as Storybook say they have backwards support for some addons but then in practice it doesn't really work.

It's a bigger ticket than this for future proofing/maintenance issue. So I'd suggest removing this from the spring and editing this ticket or creating a new one.

What should be done: 
- upgrade Storybook to latest release (6.1.?)
- ensure all addons we use are updated or we keep the functionality with a different addon (eg. info-addon => docs-addon)
- rewrite our story components (everything ending in `*.stories.tsx`) to use the new [CSF format](https://storybook.js.org/docs/react/api/csf)

Then our development will be aligned with how Storybook is developing (all their good documentation will be relevant again for any devs that are writing stories) and also all the usual bug fixes that come up with a major upgrade.

rewriting the components is time consuming but should be straightforward. It's a matter of rewriting them in a different style.
There is a codemod which is a script to do it automatically but when I briefly tried it, I had no luck.

**Comment by rosibaj** [comment]
@ciaranschutte makes sense, this sounds good! i will make these tickets for backlog and get this out of the sprint!

**Comment by ciaranschutte** [comment]
@rosibaj thank you

**Comment by ciaranschutte** [comment]
storybook has been removed from platform
