### ISSUE TITLE
File Entity: Updates for first release

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2090]
We need to make some changes to the File Entity page so that 
1. We can release a first version, while we work on clinical additions
2. It's consistent with the data in the file repository 
(I confirmed all of the field label changes and additions with Hardeep and Linda)

Zeplin: https://zpl.io/an8jpLl

### Field Label Updates for consistency
- [x] 1. Change `File Format` to `File Type`
- [x] 2. Change `Size` to `File Size`
- [x] 3. Change `Access` to `File Access`
- [x] 4. Change `Workflow Type` to `Workflow Name` (link details are outlined in https://github.com/icgc-argo/platform-ui/issues/2105)
- [x] 5. Change `Software` to `Analysis Tools`
- [x] As discussed, when `File Access=Open`, let's change the icon to an unlocked icon

### Hook Up the following fields
- [x] 6. Hook up `File ID` in the title bar instead of the longer `Object ID`
- [x] 7. `File ID` in the table
- [x] 8. `Program` - this may be coming from program services - but can we **display the full name of the program** then the `Program ID` in brackets.  (link details are outlined in https://github.com/icgc-argo/platform-ui/issues/2105)
- [x] 9. `Data Type`
- [x] 10. `Genome Build` ; Linda says this will stay as GRCh38 only for a while. (link details are outlined in https://github.com/icgc-argo/platform-ui/issues/2105)
- [x] 11. `Analysis Tools` (this used to be called Software) - also this can have multiple values so display in the table cell as comma separated.
- [x] 12. `Submitted Donor ID`
- [x] 13. Hook up `Matched Normal Submitter Sample ID` (this will just be for tumours)

### Add and hookup
- [x] 14. Add `Data Category` and hookup
- [x] 15. Add `Genome Annotation` and hookup. 
**NOTE** this will only be populated for `RNA-Seq` data, and `N/A` otherwise. We currently don't have an RNA pipeline, so this field will be N/A for all current files.
- [x] 16. Add `Workflow Version` and hookup (link details are outlined in https://github.com/icgc-argo/platform-ui/issues/2105)
- [x] 17. Add `Specimen Type` and hookup
![image](https://user-images.githubusercontent.com/18424138/143476784-d864aa08-daf6-46be-8a76-d9af5827fd89.png)

### Hide/Remove
- [x] 18. Hide the File download button in top header
NOTE: The legend component will be described in this ticket: https://github.com/icgc-argo/platform-ui/issues/2108
- [x] 19. Hide the Donor tabs, a file will only be associated to one donor for now.
- [x] 20. Remove all links in the Associated Donors card (donor id, specimen id, sample id, matched normal id links)
- [x] 21. Hide the clinical fields under the donor IDs: `Primary Site`, `Cancer Type` and `Age at Diagnosis`
- [x] 22. If `Tumour Normal Designation`: **Normal** then hide `Matched Normal Submitter Sample ID` AND the divider line.
![image](https://user-images.githubusercontent.com/18424138/143138163-bda2acc1-b93d-4281-9aeb-4bb29954353d.png)

**Comment by kcullion** [comment]
@mistryrn @akachru-github I think once this ticket is finished it would make sense to do this related one before getting to the small file download tickets
https://github.com/icgc-argo/platform-ui/issues/2105

**Comment by kcullion** [comment]
@mistryrn as discussed, let me know when you need the opened lock logo - this will be the icon to show for `File Access = Open`

**Comment by mistryrn** [comment]
Re: "Open Lock" icon

The icon will be temporarily added directly to the page in `platform-ui` while we wait for the new UIKit to be ready.

Once it's ready, the icon will be added to UIKit in https://github.com/icgc-argo/uikit/issues/26 and we will switch to using the new UIKit icon on this page here https://github.com/icgc-argo/platform-ui/issues/2136

**Comment by mistryrn** [comment]
@kcullion the items which aren't checked are going to be addressed in #2105

**Comment by kcullion** [comment]
This looks great @mistryrn ! 
I'm going to add one piece of feedback to the continuation ticket: https://github.com/icgc-argo/platform-ui/issues/2105 

I would like Linda to test this page too to make sure all the data is looking correct - but I'll wait to ask her on that 2105 ticket too.

**Comment by kcullion** [comment]
this page is working as expected in staging
