### ISSUE TITLE
[UI] Submitted data: Filters and search bar

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2260]
## Goal
**Static UI** for the card that holds the title, quickfilters, searchbox and download button

**Making these items work will be done in these tickets:**
Hook up the quick filters: https://github.com/icgc-argo/platform-ui/issues/2268
Hook up the donor search: https://github.com/icgc-argo/platform-ui/issues/2269
Hook up the download buttons: https://github.com/icgc-argo/platform-ui/issues/2271

## Expected Outcomes
Zeplin: https://zpl.io/p1rLJQl
By default, this bar looks like this: 
![image](https://user-images.githubusercontent.com/18424138/160157544-df5076c9-3559-424d-bb0e-00cc709b6c5c.png)
- [x] 1. Title says "Clinical Data for:" and by default says "All Donors" (this is dynamic, see below the other cases)
- [x] 2. A dropdown displays quick filters, with values as shown in mockup (functionality to be done here: https://github.com/icgc-argo/platform-ui/issues/2268)
- [x] 3. A searchbox will allow the user to search by donor id (similar to one built in file repo facet panel) functionality to be done here https://github.com/icgc-argo/platform-ui/issues/2269 
- [x] 4. A "List" button will eventually trigger the modal in another ticket (https://github.com/icgc-argo/platform-ui/issues/2261)
- [x] 5. A Download "Clinical Data" button. Hooked up in this ticket; https://github.com/icgc-argo/platform-ui/issues/2271

**Extra customizations**:
Zeplin: https://zpl.io/RMBrxMn

When the user filters this submitted data section, some new items may change or show up
![image](https://user-images.githubusercontent.com/18424138/160158496-b048e04e-bc2b-4644-a771-7281cfde1424.png)

- [x] 7. A "Clear Filters" link will appear when the submitted data section is filtered and isn't showing all donors
- [x] 8. If the section is filtered on one donor id, show this id in the search box too and an "x" icon to clear it

**Comment by Buwujiu** [comment]
Tested in QA, working as expected! Thank you @daniel-cy-lu
