### ISSUE TITLE
UI Component Library: Vertical Tabs 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#649]
The UI component library need to have a set of vertical tabs. 

All of the states for vertical tabs:

- [ ]   Default
- [ ]   Hover
- [ ]   Active
- [ ]  Label spans on more than one line
- [ ]   With badge (can be red with "!", yellow with # rows of that file, or green with # rows of that file)

![Screen Shot 2019-09-25 at 4 48 31 PM](https://user-images.githubusercontent.com/18424138/65638624-7ca7f480-dfb4-11e9-9f91-132c10078b65.png)

See Zeplin: https://zpl.io/adzPEOR

- [ ] Grey divider line that goes "under" the active tab
![Screen Shot 2019-09-25 at 4 52 41 PM](https://user-images.githubusercontent.com/18424138/65638824-f2ac5b80-dfb4-11e9-98d8-8d2e604e3fb0.png)

Example mock: https://zpl.io/2ZXEgAL

**Comment by kcullion** [comment]
Looking great @hlminh2000 !

Some fixes:
- [ ] Badges - these were meant to use the same styles as the "tag" component: https://argo-ui-storybook.netlify.com/?path=/story/uikit-tag--basic. They look larger in the tabs. can we use the tag styles please

**Colours for accessibility.** @rosibaj confirmed, these badges are fine to not pass the accessibility test because they are more of a nice-to-have and the number is available elsewhere on the UI: 
- [ ] blue text for active tab state..please change to the darker blue: #045093
- [ ] Please use the darker green for the badge background: #00C79D (this may be a new brand colour that hasn't been implemented yet but it's here: https://zpl.io/2pvln6N) 
- [ ] the blue badge should be the lighter blue accent colour (not the secondary colour). So the dark version of this should be #00B3D3

- [ ] In storybook can we combine the tab components? So under Tabs have Horizontal and Vertical.

**Comment by kcullion** [comment]
This feedback has been moved to: https://github.com/icgc-argo/platform-ui/issues/729
@rosibaj did you want to close this ticket?

**Comment by rosibaj** [comment]
@kcullion yup! thanks @hlminh2000 looking good so far!!
