### ISSUE TITLE
Vertical Tabs Improvements

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/platform-ui#729]
Some fixes:
- [x] Badges - these were meant to use the same styles as the "tag" component: https://argo-ui-storybook.netlify.com/?path=/story/uikit-tag--basic. They look larger in the tabs. can we use the tag styles please

- [x] the wrong font size is being used..should be the "data" font type: font-size:12px

**Colours for accessibility.** @rosibaj confirmed, these badges are fine to not pass the accessibility test because they are more of a nice-to-have and the number is available elsewhere on the UI: 
- [x] blue text for active tab state..please change to the darker blue: #045093 (secondary_dark)
- [x] Please use the darker green for the badge background: #00C79D (this is a new colour that I found we needed. Let's name it #accent1_dimmed) 
- [x] the blue badge should be the lighter blue accent colour (not the secondary colour). So the dark version of this should be #00B3D3 (#accent3_dark)

- [x] The "!" icon doesn't really read as an exclamation mark here - maybe too small. Can you use the svg from sketch? (fix in page)

- [x] In storybook can we combine the tab components? So under Tabs have Horizontal and Vertical. (don't have to if that effects the code)

**Comment by rosibaj** [comment]
@ciaranschutte lgtm!  Thank you!!!
